title: Vivek Handebagh
email: viveksimha@gmail.com
description: "Vivek's digital garden."
baseurl: "" # leave empty for user pages, or use "/repo-name" for project pages
url: "https://vivekhandebagh.github.io" # update with your GitHub pages URL

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
